check that voms-proxy-info knows where certs are

diff --git a/.github/workflows/gh-ci.yml b/.github/workflows/gh-ci.yml
--- a/.github/workflows/gh-ci.yml
+++ b/.github/workflows/gh-ci.yml
@@ -34,7 +34,14 @@ jobs:
 
     - name: Make sure voms tools are working
       run: |
-        docker run ${DOCKER_ORG}/${IMAGE}:PR voms-proxy-info
+        ERROR=$(docker run ${DOCKER_ORG}/${IMAGE}:PR voms-proxy-info 2>&1 > /dev/null)
+        TEST=$(echo -e "\nCouldn't find a valid proxy.\n")
+
+        if [ "$ERROR" == "$TEST" ]; then
+          exit 0
+        else
+          exit 1
+        fi
 
     - name: Export Full Conda Environment
       run: |
